### PR TITLE
Setup pre-commit to run codespell

### PR DESCRIPTION
**Pull request by cclauss**
Eat our own dogfood...

Related to:
*  #71

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks. @DimitriPapadopoulos post this PRs merge I will rebase mine to this commit to fix the precommit check.

**Comment by cclauss** [comment]
@kbdharun You could also add these changes to you PR and then we can close this one.

**Comment by kbdharun** [comment]
> @kbdharun You could also add these changes to your PR and then we can close this one.

Done

**Comment by cclauss** [comment]
Closing in favor of #71 which contains these changes.
* #71

**Pull request closed without merging**
