### PR TITLE
Only run bats diagnostics on failure

### PR DESCRIPTION
**Pull request by peternewman**

### CODE REVIEW

**Comment by peternewman** [comment]
See for example:
https://github.com/codespell-project/actions-codespell/runs/1811400669?check_suite_focus=true

From #27

**Comment by larsoner** [comment]
I don't totally understand BATS but looks reasonable to me!

**Comment by peternewman** [comment]
It's like pytest, but for shell commands, only without any of the useful diagnostics when the tests break to see the value of the two sides of the equality test for example, hence this workaround.

**Comment by peternewman** [comment]
I've just realised this isn't quite as simple as it should be, but probably still better than nothing!

**Pull request merged**
