### PR TITLE
Add the skip option

### PR DESCRIPTION
**Pull request by peternewman**
This is sufficient to dog food:
https://github.com/codespell-project/codespell/blob/ac9e18a3ecd7021d2dbbea40f4c0a30a5d5d449d/.github/workflows/codespell.yml#L13

### CODE REVIEW

**Comment by peternewman** [comment]
@per1234 would you mind taking a look at my first new bats test (now it's working)?

**Comment by larsoner** [comment]
CIs are failing

**Comment by peternewman** [comment]
> CIs are failing

I think this is because @per1234 was testing for buggy behaviour. I expect we should fix the other things he found, then ship the next release then this will come good...

**Comment by peternewman** [comment]
I think this should be merge-able now @larsoner .

**Comment by peternewman** [comment]
Having debugged it (grumble @per1234 :stuck_out_tongue_winking_eye: ) it's because our behaviour for hidden files in directories has changed.

**Pull request merged**
